permalink: pretty

nav:
  - text: About Us
    url: /
  - text: Arts
    url: /arts/
  - text: Blog
    url: /blog/
  - text: Business
    url: /business/
  - text: Design
    url: /design/
  - text: Editorial
    url: /editorial/
  - text: Magazine
    url: /magazine/
  - text: News
    url: /news/
  - text: Multimedia
    url: /multimedia/
  - text: Sports
    url: /sports/
  - text: Tech
    url: /tech/

season: Spring
year: 2025
subtitle: Spring Comp 2025

num_years_crimson_existed: 152

monthly_page_views_millions: 1.75
yearly_page_views_millions: 21
yearly_page_time_spent_years: 58

google_doc_signup: https://docs.google.com/forms/d/e/1FAIpQLSeWqAvqCBrv2hdbVIaavzapgI-Sbhjov2De7O6Ds4qPmoTWPQ/viewform?usp=header
facebook_rsvp_link: https://www.facebook.com/events/515215159346903/

president: McKenna E. McKrell
managing_editor: Tilly R. Robinson
business_manager: Jack D. Jassy

arts:
  dir1:
    name: Hannah M. Wilkoff
    email: hannah.wilkoff@thecrimson.com
  dir2:
    name: Makenna J. Walko
    email: makenna.walko@thecrimson.com

blog:
  dir1:
    name: Ava H. Rem
    email: ava.rem@thecrimson.com
  dir2:
    name: Wyatt G Croog
    email: wyatt.croog@thecrimson.com

business:
  dir1:
    name: Ella S. Dotzler
    email: ella.dotzler@thecrimson.com
  dir2:
    name: Ben H. Morrison
    email: ben.morrison@thecrimson.com

design:
  dir1:
    name: Nicole M. Hernández Abud
    email: nicole.hernandez@thecrimson.com
  dir2:
    name: Alexandra M. Kneiss
    email: alex.kneiss@thecrimson.com

editorial:
  dir1:
    name: Violet T.M. Barron
    email: violet.barron@thecrimson.com
  dir2:
    name: Julia S. Dan
    email: julia.dan@thecrimson.com
  dir3:
    name: Heidi S. Enger
    email: heidi.enger@thecrimson.com

magazine:
  dir1:
    name: Xinni (Sunshine) Chen
    email: sunshine.chen@thecrimson.com
  dir2:
    name: Kate J. Kaufman
    email: kate.kaufman@thecrimson.com

news:
  dir1:
    name: Azusa M. Lippit
    email: azusa.lippit@thecrimson.com
  dir2:
    name: Asher J. Montgomery
    email: asher.montgomery@thecrimson.com

multimedia:
  dir1:
    name: Lotel L. Loeb
    email: lotem.loeb@thecrimson.com
  dir2:
    name: Hugo C. Chiasson
    email: hugo.chiasson@thecrimson.com

sports:
  dir1:
    name: Isabel C. Smail
    email: isabel.smail@thecrimson.com
  dir2:
    name: Reed M. Trimble
    email: reed.trimble@thecrimson.com

technology:
  dir1:
    name: Carly Y. Chen
    email: carly.chen@thecrimson.com
  dir2:
    name: Milan Naropanth
    email: milan.naropanth@thecrimson.com
