permalink: pretty

nav:
  - text: About Us
    url: /
  - text: Arts
    url: /arts/
  - text: Blog
    url: /blog/
  - text: Business
    url: /business/
  - text: Design
    url: /design/
  - text: Editorial
    url: /editorial/
  - text: Magazine
    url: /magazine/
  - text: News
    url: /news/
  - text: Multimedia
    url: /multimedia/
  - text: Sports
    url: /sports/
  - text: Tech
    url: /tech/

season: Spring
year: 2022
subtitle: Spring Comp 2022

num_years_crimson_existed: 149

monthly_page_views_millions: 1.5
yearly_page_views_millions: 16.1
yearly_page_time_spent_years: 58

google_doc_signup: https://docs.google.com/forms/d/e/1FAIpQLSd2lXFoh-5Xo7FIuOM2yT8y05GST95UZ3U5pc_E2G7kyMrUoQ/viewform 
facebook_rsvp_link: https://www.facebook.com/events/515215159346903/

president: Raquel Coronell Uribe
managing_editor: Jasper G. Goodman
business_manager: Amy Zhou

arts:
  dir1:
    name: Isabella B. Cho
    email: isabella.cho@thecrimson.com
  dir2:
    name: Anya L. Henry
    email: anya.henry@thecrimson.com

blog:
  dir1:
    name: Tina Chen
    email: tina.chen@thecrimson.com
  dir2:
    name: Matylda A. Urbaniak
    email: matylda.urbaniak@thecrimson.com

business:
  dir1:
    name: Alex L. Luchtenberg
    email: alex.luchtenberg@thecrimson.com
  dir2:
    name: Jack K. Weldon
    email: jack.weldon@thecrimson.com

design:
  dir1:
    name: Helen H. Wang
    email: helen.wang@thecrimson.com
  dir2:
    name:  Isabel W. Brown 
    email: isabel.brown@thecrimson.com

editorial:
  dir1:
    name: Gordon J. Ebanks
    email: gordon.ebanks@thecrimson.com
  dir2:
    name: Libby Tseng
    email: libby.tseng@thecrimson.com

magazine:
  dir1:
    name: Maliya V. Ellis
    email: maliya.ellis@thecrimson.com
  dir2:
    name: Garrett W. O'Brien
    email: garrett.o'brien@thecrimson.com

news:
  dir1:
    name: Juliet E. Isselbacher
    email: juliet.isselbacher@thecrimson.com
  dir2:
    name: Alex M. Koller
    email: alex.koller@thecrimson.com

multimedia:
  dir1:
    name: Andrew Lu
    email: andrew.lu@thecrimson.com
  dir2:
    name: Angela Dela Cruz
    email: angela.delacruz@thecrimson.com

sports:
  dir1:
    name: Zing Gee
    email: zing.gee@thecrimson.com
  dir2:
    name: Noah Jun
    email: noah.jun@thecrimson.com

technology:
  dir1:
    name: Naomi Kenyatta
    email: naomi.kenyatta@thecrimson.com
  dir2:
    name: Kevin Luo
    email: kevin.luo@thecrimson.com
