permalink: pretty

nav:
  - text: About Us
    url: /
  - text: Arts
    url: /arts/
  - text: Blog
    url: /blog/
  - text: Business
    url: /business/
  - text: Design
    url: /design/
  - text: Editorial
    url: /editorial/
  - text: Magazine
    url: /magazine/
  - text: News
    url: /news/
  - text: Multimedia
    url: /multimedia/
  - text: Sports
    url: /sports/
  - text: Tech
    url: /tech/

season: Spring
year: 2024
subtitle: Spring Comp 2024

num_years_crimson_existed: 150

monthly_page_views_millions: 1.75
yearly_page_views_millions: 21
yearly_page_time_spent_years: 58

google_doc_signup: https://forms.gle/Gm15JiDJ1fJzPsWr7
facebook_rsvp_link: https://www.facebook.com/events/515215159346903/

president: J. Sellers Hill
managing_editor: Miles J. Herszenhorn
business_manager: Matthew M. Doctoroff

arts:
  dir1:
    name: Thomas A. Ferro
    email: thomas.ferro@thecrimson.com
  dir2:
    name: Stella A. Gilbert
    email: stella.gilbert@thecrimson.com

blog:
  dir1:
    name: Laasya N. Chidurappa
    email: laasya.chidurappa@thecrimson.com
  dir2:
    name: Arezoo Ghazagh
    email: arezoo.ghazagh@thecrimson.com

business:
  dir1:
    name: Mina H. Raj
    email: mina.raj@thecrimson.com
  dir2:
    name: Lilian C. Smith
    email: lilian.smith@thecrimson.com

design:
  dir1:
    name: Julia B. Freitag
    email: julia.freitag@thecrimson.com
  dir2:
    name:  Stephanie Nguyen 
    email: stephanie.nguyen@thecrimson.com

editorial:
  dir1:
    name: Ellie Ashby
    email: ellie.ashby@thecrimson.com
  dir2:
    name: Hea Pushpraj
    email: hea.pushpraj@thecrimson.com

magazine:
  dir1:
    name: Adelaide E. Parker
    email: adelaide.parker@thecrimson.com
  dir2:
    name: Jem K. Williams
    email: jem.williams@thecrimson.com

news:
  dir1:
    name: Rahem D. Hamid
    email: rahem.hamid@thecrimson.com
  dir2:
    name: John N. Peña
    email: john.pena@thecrimson.com

multimedia:
  dir1:
    name: Maria S. Cheng 
    email: maria.cheng@thecrimson.com
  dir2:
    name: Jina H. Choe
    email: jina.choe@thecrimson.com

sports:
  dir1:
    name: Jack Canavan
    email: jack.canavan@thecrimson.com
  dir2:
    name: Nadia A. Fairfax
    email: nadia.fairfax@thecrimson.com

technology:
  dir1:
    name: Neil Shah
    email: neil.shah@thecrimson.com
  dir2:
    name: Dennis Eum
    email: dennis.eum@thecrimson.com
