permalink: pretty

nav:
  - text: About Us
    url: /
  - text: Arts
    url: /arts/
  - text: Blog
    url: /blog/
  - text: Business
    url: /business/
  - text: Design
    url: /design/
  - text: Editorial
    url: /editorial/
  - text: Magazine
    url: /magazine/
  - text: News
    url: /news/
  - text: Multimedia
    url: /multimedia/
  - text: Sports
    url: /sports/
  - text: Tech
    url: /tech/

season: Spring
year: 2023
subtitle: Spring Comp 2023

num_years_crimson_existed: 149

monthly_page_views_millions: 1.5
yearly_page_views_millions: 16.1
yearly_page_time_spent_years: 58

google_doc_signup: https://docs.google.com/forms/d/e/1FAIpQLSd8Mzy0GMllJg-uxhhrKd7EjmwNNCI5ka33ORZNxZ1by5xZ2Q/viewform 
facebook_rsvp_link: https://www.facebook.com/events/515215159346903/

president: Cara J. Chang
managing_editor: Brandon L. Kingdollar
business_manager: Cynthia V. Lu

arts:
  dir1:
    name: Anna Moiseieva
    email: anna.moiseieva@thecrimson.com
  dir2:
    name: Monique I. Vobecky
    email: monique.vobecky@thecrimson.com

blog:
  dir1:
    name: Elizabeth K. Roosevelt
    email: elizabeth.roosevelt@thecrimson.com
  dir2:
    name: Anjali Z. Mehta
    email: anjali.mehta@thecrimson.com

business:
  dir1:
    name: Penelope M. Alegria
    email: penelope.alegria@thecrimson.com
  dir2:
    name: Yab G. Demisie 
    email: yab.demisie@thecrimson.com

design:
  dir1:
    name:  Isabel W. Brown 
    email: isabel.brown@thecrimson.com
  dir2:
    name: Helen H. Wang
    email: helen.wang@thecrimson.com

editorial:
  dir1:
    name: Tommy Barone
    email: tommy.barone@thecrimson.com
  dir2:
    name: Ruby Huang
    email: ruby.huang@thecrimson.com

magazine:
  dir1:
    name: Mila G. Barry
    email: mila.barry@thecrimson.com
  dir2:
    name: Jade Lozada
    email: jade.lozada@thecrimson.com

news:
  dir1:
    name: Isabella B. Cho
    email: isabella.cho@thecrimson.com
  dir2:
    name: Vivi E. Lu
    email: vivi.lu@thecrimson.com

multimedia:
  dir1:
    name: Joey Huang
    email: joey.huang@thecrimson.com
  dir2:
    name: Julian J. Giordano
    email: julian.giordano@thecrimson.com

sports:
  dir1:
    name: Christopher D. Wright
    email: christopher.wright@thecrimson.com
  dir2:
    name: Caroline G. Gage
    email: caroline.gage@thecrimson.com

technology:
  dir1:
    name: Naomi Kenyatta
    email: naomi.kenyatta@thecrimson.com
  dir2:
    name: Wittman Goh
    email: wittman.goh@thecrimson.com
